## Лабораторная работа №1 -> Numpy


---



In [12]:
import numpy as np

# Функция для генерации случайных данных
def generate_sales_data(num_entries=10, seed=42):
    np.random.seed(seed)  # Фиксируем случайность
    item_ids = np.random.randint(100, 110, size=num_entries)  # ID товаров (100-109)
    quantities = np.random.randint(1, 10, size=num_entries)   # Количество проданных единиц (1-9)
    prices = np.random.uniform(50, 500, size=num_entries)     # Цена за единицу (50.0 - 500.0)
    return np.column_stack((item_ids, quantities, prices))  # Объединяем в один массив

**Укажите ваш вариант и количество семплов**

In [13]:
# Мой вариант
variant = 1
samples = 10
data = generate_sales_data(num_entries=samples, seed=variant)
data

array([[105.        ,   3.        , 113.17412237],
       [108.        ,   5.        , 139.14567009],
       [109.        ,   6.        , 410.3350559 ],
       [105.        ,   3.        , 485.71770907],
       [100.        ,   5.        , 191.04088017],
       [100.        ,   3.        , 361.54517705],
       [101.        ,   5.        , 444.37511853],
       [107.        ,   8.        , 452.57299858],
       [106.        ,   8.        ,  88.26989512],
       [109.        ,   2.        ,  67.57465245]])

In [14]:
'''
Скоре всего понадобятся данные сгруппиранные по ID,
этого подготовим отдельный массив с уникальными ID и суммой дохода
'''
unique_ids = np.unique(data[:, 0])
revenue_by_id = []
count_by_id = []
for id in range(len(unique_ids)):
    revenue_by_id = np.append(revenue_by_id,sum(data[:,2][data[:,0] == unique_ids[id]]))
    count_by_id = np.append(count_by_id,sum(data[:,1][data[:,0] == unique_ids[id]]))
    total_revenue = revenue_by_id * count_by_id

data_group_id = np.column_stack((unique_ids,count_by_id,revenue_by_id,total_revenue))
data_group_id

array([[ 100.        ,    8.        ,  552.58605722, 4420.68845778],
       [ 101.        ,    5.        ,  444.37511853, 2221.87559267],
       [ 105.        ,    6.        ,  598.89183144, 3593.35098865],
       [ 106.        ,    8.        ,   88.26989512,  706.15916093],
       [ 107.        ,    8.        ,  452.57299858, 3620.58398861],
       [ 108.        ,    5.        ,  139.14567009,  695.72835044],
       [ 109.        ,    8.        ,  477.90970836, 3823.27766687]])

## Задание:

Вы работаете с данными о продажах интернет-магазина. Ваша задача — обработать и проанализировать массив данных с использованием только библиотеки `numpy`.

**Исходные данные:**

Данные представлены в виде 2D-массива numpy, где:

	•	Столбец 0 — ID товара
	•	Столбец 1 — Количество проданных единиц
	•	Столбец 2 — Цена за единицу

например:

```
array([[105.        ,   3.        , 113.17412237],
       [108.        ,   5.        , 139.14567009],
       [109.        ,   6.        , 410.3350559 ],
       [105.        ,   3.        , 485.71770907],
       [100.        ,   5.        , 191.04088017],
       [100.        ,   3.        , 361.54517705],
       [101.        ,   5.        , 444.37511853],
       [107.        ,   8.        , 452.57299858],
       [106.        ,   8.        ,  88.26989512],
       [109.        ,   2.        ,  67.57465245]])
```



**1.	Общая выручка**

Рассчитайте общую выручку магазина

In [15]:
# ваш код здесь
print(f'Общая выручка: {np.round(np.sum(data[:,1] * data[:,2]),2)}')

Общая выручка: 13678.02


**2.	Общая выручка по каждому товару**

Выведите общую выручку для каждого уникального товара (по ID).

In [22]:
# ваш код здесь
for i in range(len(data_group_id[:,0])):
    print(f"Для ID {data_group_id[i,0]} товара, выручка была: {np.round(data_group_id[i,3],2)}")


Для ID 100.0 товара, выручка была: 4420.69
Для ID 101.0 товара, выручка была: 2221.88
Для ID 105.0 товара, выручка была: 3593.35
Для ID 106.0 товара, выручка была: 706.16
Для ID 107.0 товара, выручка была: 3620.58
Для ID 108.0 товара, выручка была: 695.73
Для ID 109.0 товара, выручка была: 3823.28


**3. Товар приносящий самую большую выручку**

Определите ID товара, который принес наибольшую выручку.

In [6]:
# ваш код здесь
index_max_price = np.argmax(data_group_id[:,3])
print(f'ID {data_group_id[index_max_price,0]} товара, который принес наибольшую выручку: {round(data_group_id[index_max_price,3],2)}')

ID 100.0 товара, который принес наибольшую выручку: 4420.69


**4. Средневзвешанная цена проданных товаров**

Рассчитайте среднюю цену проданных товаров, взвешенную по их количеству.

In [7]:
# ваш код здесь
marks = data[:,2]
weights = data[:,1]

weighted_avg = np.average(marks, weights=weights)
print("Средневзвешенное:", round(weighted_avg,2))

Средневзвешенное: 284.96


**5. Товар с наибольшим количеством продаж**

Найдите ID товара, который был продан в наибольшем количестве.


In [8]:
# ваш код здесь
index_max_count = np.argmax(data_group_id[:,2])
print(f'ID {data_group_id[index_max_count,0]} товара, который был продан в наибольшем количестве: {round(data_group_id[index_max_count,1],0)} раз')

ID 105.0 товара, который был продан в наибольшем количестве: 6.0 раз


**6. Товар с наименьшим количеством продаж**

Найдите ID товара, который был продан в наименьшем количестве.


In [9]:
# ваш код здесь
index_min_count = np.argmin(data_group_id[:,1])
print(index_min_count)
print(f'ID {data_group_id[index_min_count,0]} товара, который был продан в наименьшем количестве: {round(data_group_id[index_min_count,1],0)} раз')

1
ID 101.0 товара, который был продан в наименьшем количестве: 5.0 раз


**7. Топ-3 самых продаваемых товаров**

Выведите ID товаров, которые были проданы в наибольшем количестве единиц.

In [10]:
# ваш код здесь
order_count = np.sort(data_group_id[:,1], )[::-1]
index_vec = np.array([0,1,2])
order_count= np.unique(order_count[index_vec])
index = []

for i in range(len(order_count)):
    round = np.where(data_group_id[:,1] == order_count[i])
    index = np.append(index,round)

if len(index>3):
    print("NB! Значений более 3х!")
    index = index[index_vec]

print("Топ-3 самых продаваемых")
for i in range(len(index)):
    print(data_group_id[i,0])



NB! Значений более 3х!
Топ-3 самых продаваемых
100.0
101.0
105.0


**8. Медианная цена проданных товаров**

Выведите медианную цену всех проданных товароов

In [23]:
# ваш код здесь
print(f'Медианная цена всех проданных товаров: {np.round(np.median(data[:,2]),2)}')


Медианная цена всех проданных товаров: 276.29
