## Основы NumPy: массивы и векторные вычисления.ipynb

Загрзить numpy с псевдонимом

In [ ]:
# Загрзить numpy с псевдонимом

Создать data:
array([[3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
# Создать data:
# array([[3., 4., 5.],
#        [6., 7., 8.]])

Прибавить 2
array([[ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [ ]:
# Прибавить 2
# array([[ 5.,  6.,  7.],
#        [ 8.,  9., 10.]])

Умножить на 2
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [ ]:
# Умножить на 2
# array([[ 2.,  4.,  6.],
#        [ 8., 10., 12.]])

 поэлементное сложение элементов
 array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [ ]:
#  поэлементное сложение элементов
#  array([[ 2.,  4.,  6.],
#        [ 8., 10., 12.]])

 поэлементное умножение элементов
 array([[ 9., 16., 25.],
       [36., 49., 64.]])

поэлементное сравнение
array([[ True,  True,  True],
       [ True,  True,  True]])

поэлементное сравнение
array([[False, False, False],
       [False, False, False]])

Создать data
array([[[1., 2., 3.],
        [4., 5., 6.]]])

Получить размерность объекта

Создать vector ось 1.0, 2.0, 4.0, 8.0

Создать matrix матрицу 1.0, 2.0 и 4.0, 8.0

Получить 3хмерный массив 
[[[1. 2.]
  [4. 8.]]]

вывести размерность
1) вектора,
2) матрицы
3) 3х мернргого массивыв

Выввести тип данных matrix

Вывести тип объекта matrix

Вывести байты объекта matrix

Изменить matrix на int32
Вывести matrix
Вывести байты объектов

создать arr [1.0, np.nan, 3.0, np.nan]

Проверить на nan

Создать array2d 
[
    [0.0, 0.1, 0.2], 
    [1.0, 1.1, 1.2], 
    [2.0, 2.1, 2.2]
    ]

Вывести 2й вектор из array2d

вывести 2ое значене из 2ого вектора

вывестий 2й вектор, затем его 2ое число

Создать arr
[[0,1,2],[3,4,5],[6,7,8]]

Вывести срез 3й строки

Выполнить умножение 3 строки и внести в arr
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [24, 28, 32]])

Получить
array([[ 1],
       [ 4],
       [28]])

Создать:
["Sergey", "Ivan", "Ivan", "Sergey", "Alexey", "Dmitrij", "Pavel"]
Создать масу по "Sergey"

создать  numbers [1, 2, 3, 4, 5, 6, 7] и пременить предыдущую маску

Создать масу по "Sergey" или "Ivan"

применить маску к numbers

инверсию маски

Создать arr [10, 20, 30, 40, 50]
Создать indices [0, 2, 4]
применить indices к arr

изменить indices [4, 0, 0] и применить к arr

Создаем 2мерный массив
[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
Создаем индекси по строкам и колонкам, чтобы забрать 2 и 9

Создать arr [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Транспонировать его

A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])

перемножить 3мя способами

v1 = np.array([1, 2, 3, 4])
v2 = np.array([4, 3, 2, 1])

перемножить

Матрица (2,3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

Вектор (3,)
v = np.array([10, 20, 30])

1) перемножить в result
2) вывести в result
3) получить размерность result

[140 320]
(2,)


data = np.array([1, 2, 2, 2, 3, 4, 4, 4, 1])

1) Среднее значение
2) Медиана
3) Минимальное значение
4) Максимальное значение
5) Сумма элементов

Индекс максимального элемента

Индекс минимального элемента


Стандартное отклонение
Дисперсия


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

1) Сумма по столбцам (axis=0)
2) Среднее по строкам (axis=1)
3) Максимум по всей матрице


data = np.array([10, 20, 30, 40, 50])

25-й процентиль (первый квартиль)
Медиана (50-й процентиль)
90-й процентиль

X = np.array([1, 2, 3, 4, 5])
Y = np.array([5, 4, 3, 2, 1])

1) Матрица корреляции
2) Матрица ковариации


marks = np.array([5.0, 4.0, 5.0, 3.0, 5.0]) 
weights = np.array([1.0, 1.5, 1.0, 2.0, 1.0])

посчитать средневзвешанное

data = np.array([2, 2, 3, 5, 5, 5])

посчитать уникальные и их частоту

Посчитать накопленную сумму

data = np.array([1, 2, 3, 4, 5, 6])